# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ZLy6TP7f-pHUfESjG2__iBucB-32TYN
"""

# Python Script to Load Saved Keras Model and Obtain Prediction from Model
import os
from os import listdir, makedirs
from os.path import join, exists, expanduser
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential, Model
from keras.layers import Dense, GlobalAveragePooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras import backend as K
import tensorflow as tf
import cv2
import numpy as np
from keras.models import load_model

# Load model
model = load_model('D:/04.Uni_Related/L6/FYP/Photobuddy_Working_Version/Fyp_BE/resnet50.h5')

# Load Image
data=[]
# image_filename = 'D:/FYP/Phaedra_BE/65d.jpg'
image_filename = 'D:/FYP/Phaedra_BE/77k.jpg'

image = cv2.imread(image_filename)
image = cv2.resize(image, (128,128), interpolation = cv2.INTER_AREA)

data.append(image)

imgs = np.asarray(data).astype('float32')

print()
print("img.shape is.....")
print(imgs.shape)

# Predict on Model
predictions = model.predict(imgs)

print()
print("Prediction is...")
print(predictions)